### ISSUE TITLE
Unicode characters width

### ISSUE THREAD

**Issue by gpakosz** [ryanoasis/powerline-extra-symbols#10]
Hello,

I'm curious about the following behavior:
![image](https://user-images.githubusercontent.com/553208/57716264-e1ebf080-7678-11e9-9a7a-8047700d9d40.png)

This is macOS `10.14.4` running iTerm2 build `Build 3.2.9` using Unicode version 9 widths.

As you can see, the two `U+E0B8` and `U+E0BE` symbols don't have the same width.
Is this a thing controlled by the font? Or is the width assign to codepoint ranges by the Unicode standard?

Thanks

**Comment by ryanoasis** [comment]
This is because these characters are 'ambiguous width', you can adjust how the terminal treats ambiguous width characters: wide or narrow. I'd try wide.

<img width="1036" alt="GLffM" src="https://user-images.githubusercontent.com/8083459/60317113-6ee5c300-9922-11e9-8f38-41fa6d19122b.png">

**Comment by gpakosz** [comment]
Thanks, I didn't know about character in the private plane having ambiguous width: https://unicode.org/reports/tr11/#Ambiguous

**Comment by ryanoasis** [comment]
@gpakosz no worries, I didn't know that either at a point. Closing (feel free to re-open if still having issues)
