### ISSUE TITLE
Few questions regarding powerline-extra-symbols

### ISSUE THREAD

**Issue by Joe23232** [ryanoasis/powerline-extra-symbols#19]
I thinking of installing it but I have a few questions:

- How do I install it? It is unfortunately unavailable in the AUR and I am not too sure if there is a build script included?
- I wanted to add it to `lemonbar-xft`. Is it possible to get these triangle styles (on the right hand side of the taskbar)
![image](https://user-images.githubusercontent.com/34926497/86787922-f2470200-c0a8-11ea-8b77-17c2c33849a1.png)

**Comment by bam80** [comment]
@Joe23232 Sorry, what is the font here?

**Comment by Joe23232** [comment]
Do you see the triangle part at the begging of each module, do you guys have that?

**Comment by ghifarit53** [comment]
the triangle glyph is already included in the regular powerline, so you can use any regular font with powerline, 

the extra symbols here adds more glyphs like rounded, fire, legos, etc.

for the build script, you can use one from the nerdfonts repo, called `font-patcher` and use `--powerline` and `--powerlineextra` as the flag

**Comment by Joe23232** [comment]
> for the build script, you can use one from the nerdfonts repo, called font-patcher and use --powerline and --powerlineextra as the flag

Is it using bitmap fonts?

**Comment by ghifarit53** [comment]
If you want to use bitmap fonts with powerline, go check [cozette](https://github.com/slavfox/Cozette) by slavfox

**Comment by Joe23232** [comment]
I actually don't want to use bitmap fonts, I want vector fonts instead.

**Comment by ghifarit53** [comment]
then you can use the regular nerdfonts, pick one that you like from their releases page

**Comment by Joe23232** [comment]
Thanks man.

**Comment by ghifarit53** [comment]
Hello @Joe23232, please close this issue if the problem already solved

**Comment by Joe23232** [comment]
Sure mate.
