### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by BigfootN** [ryanoasis/powerline-extra-symbols#2]
Hello,

I am desperately trying to install your font, but I can't install them. I tried downloading the `otf` font in the `patched-fonts` directory and copying it in my `~/.fonts` directory, but it didn't work. The `fc-cache -vf` command doesn't seem to recognise it. When I launch a `gtk2fontsel` the font doesn't appear.

Thank you very much in advance :)

**Comment by LeonardKoenig** [comment]
From the ArchLinux wiki:

> To install fonts system-wide (available for all users), move the folder to the /usr/share/fonts/ directory. The files need to be readable by every user, use chmod to set the correct permissions (i.e. at least 0444 for files and 0555 for directories). To install fonts for only a single user, use ~/.local/share/fonts (~/.fonts/ is now deprecated).
For Xserver to load fonts directly (as opposed to the use of a font server) the directory for your newly added font must be added with a FontPath entry. This entry is located in the Files section of your Xorg configuration file (e.g. /etc/X11/xorg.conf or /etc/xorg.conf). See #Older applications for more detail.
Then update the fontconfig font cache:
````bash
     $ fc-cache -vf
````

So this part in your xorg.conf is needed:

> 
````
# Let X.Org know about the custom font directories
Section "Files"
    FontPath    "/home/$USERNAME/.local/share/fonts"
EndSection
````

and the fonts should be put into ~/.local/share/fonts as stated earlier.

**Comment by ryanoasis** [comment]
@ScriptorNY sorry you are having install troubles. Update us on if @LeonardKoenig info helps you.

@LeonardKoenig thanks for the info, I should probably update the readme to include more details or link to it.

**Comment by ScriptorNY** [comment]
Thank you very much for your quick response. 

@LeonardKoenig I'm sorry but I don't think it seems to come from my method. I tried opening the font with fontconfig and it couldn't even open it. Just to make sure I downloaded another [font](https://github.com/powerline/fonts/blob/master/FiraMono/FuraMono-Regular%20Powerline.otf), which I installed in `~/.fonts` and it worked, `fc-cache -vf` recognized it and it was available in `gtk2fontsel`. 
@LeonardKoenig I also read the wiki concerning the fonts on archlinux, but evening including the paths didn't change anything, and mostly, if I'm not wrong, to be related to older applications.

So just so you know I'm only saying that with this one I'm having some problems.
But did anyone manage install this font, if so please tell me how you did it :)

Thank you in advance and thank you all for your help and patience :)

**Comment by LeonardKoenig** [comment]
@ScriptorNY Hm, the X11-paths usually are still needed (for whatever reason) and ~/.fonts is definitely deprecated ;-)

Anyway, if it works with another fonts I'm not sure why it doesn't with this O.o
Maybe the files you downloaded are corrupted?

The only things that *should* be needed are fontconfig and xorg-font-utils. I installed it using this package:
https://aur.archlinux.org/packages/powerline-fonts/

they are also calling
````bash
mkfontscale /usr/share/fonts/TTF /usr/share/fonts/Type1
mkfontdir /usr/share/fonts/TTF /usr/share/fonts/Type1
````
as you can see here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=powerline-fonts

That's all ideas I have :/

**Comment by ryanoasis** [comment]
Some housekeeping: considering this closed, re-open if issues persist @BigfootN

Thanks again @LeonardKoenig
