### ISSUE TITLE
How to patch the symbol ?

### ISSUE THREAD

**Issue by atomic** [ryanoasis/powerline-extra-symbols#4]
Hi, is there a guide on how to patch these additional symbols to existing fonts on ryanoasis/nerd-fonts?! I havent tried all of patched fonts there, but from what I tried so far. None of them have the extra-symbols yet.

The DroidSansMono patched fonts in this repo has the extra symbols though, but no devicons and awesome icons  :(

**Comment by ryanoasis** [comment]
@atomic Can you tell me which font you downloaded?

Here is `Bitstream Vera Sans Mono Nerd Font Complete.ttf`:

![selection_04_03_16_18 40 54_804x276_001](https://cloud.githubusercontent.com/assets/8083459/13543379/a6f23d68-e238-11e5-810b-398deb379a24.png)


Actually the original powerline glyphs are missing :worried: but the 'extra' symbols are showing up for me

**Comment by atomic** [comment]
Ah, I see. Its in complete folder, I thought its in additioal-variations. I tried SourceCodePro and Inconsolata complete, The symbols appear now. the size looks out of shape.

**Comment by ryanoasis** [comment]
Yeah sorry. It is not very clear at the moment which folders are for what (have a ticket for that). Yes so you are right some fonts the glyphs are like double size and that's another thing that needs to be fixed. :smile:

**Comment by ryanoasis** [comment]
Note for others these are now included on [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) repo
